name: Validate Secret on Dev Branch

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret
        run: |
          if [ "${{ secrets.MY_SECRET }}" = "abcd" ]; then
            echo "Secret matches 'abcd'"
          else
            echo "Secret does not match 'abcd'"
          fi
